name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment to destroy"
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine Environment
        id: env
        run: |
          echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Terraform Init
        working-directory: ./terraform-ecs-envs/envs/${{ steps.env.outputs.environment }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: ./terraform-ecs-envs/envs/${{ steps.env.outputs.environment }}
        run: terraform destroy -auto-approve

